"""
NAME:      Danh Tran Hong
Student_ID:100403435
"""

# Define a recursion function to calculate power by input 2 variables base & exp
# Checking even/odd by Modulus operator, if  check% 2 == 0 , it means is even numbers, else it is odd numbers 

# Then power is calculated by formulation.


def compute_power(base, exp):
    check_even = exp % 2                                            
    if exp == 0:
        return 1
    elif check_even == 0 and exp > 0:                                    #  To compute  power which has even and postive exp value
        power = compute_power(base**2, exp // 2)
    elif check_even == 0 and exp <0:                                     # To compute  power which has even and negative exp value
        power = 1 / compute_power(base**2, -exp // 2)
    elif check_even == 1  and exp <0:                                    # To compute  power which has odd and negative exp value
        power = 1 /  (base * compute_power(base**2, (-exp - 1) // 2))
    else:                                                                # To compute  power which has odd and postive exp value
        power = base * compute_power(base**2, (exp - 1) // 2)
    return power

# check the func with negative, postive number
test_negavite = compute_power(2,-4)
test_positive = compute_power(2,4)
print(f"test_negavite = {test_negavite} \ntest_positive = {test_positive}")  # Output: 8


# make a list with name "powers" by using  function compute_power(2,x), and x variable which is generated by iteration control.
# Print the list "powers"
powers = [ compute_power(2,x) for x in range (0 ,10**3) ]
print(powers)