"""
NAME:      Danh Tran Hong
Student_ID:100403435
"""

# Define a function to calculate power by input 2 variables base & exp, the result will return to power variable.
def compute_power(base,exp):
    power = 1
    if exp > 0:                         # Check exp is postive 
        for _ in range (exp):
            power = power*base
    else:                               # Exp is negative
        for _ in range (-exp):
           power = power / base
    return power

# test with (base = 2, exp = -3) and (base = 2, exp = 3)
print(compute_power(2,-3)) 
print(compute_power(2,3)) 
# output 

# make a list with name "powers" by using  function compute_power(2,x), and x variable which is generated by iteration control.
# Print the list "powers",
powers = [ compute_power(2,x) for x in range (0 ,10**3) ]
print(powers)



